# Generated by Django 4.0.3 on 2022-05-26 01:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=40, verbose_name='tema')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('senha', models.CharField(max_length=10, verbose_name='senha')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subarea', models.CharField(max_length=30, verbose_name='subarea')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc2022.area')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, verbose_name='titulo')),
                ('resumo', models.TextField(verbose_name='resumo')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc2022.subarea')),
            ],
        ),
        migrations.CreateModel(
            name='EscolhaProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 5, 26, 1, 58, 56, 940399), verbose_name='data')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='nota')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc2022.professor')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc2022.trabalho')),
            ],
        ),
    ]
