# Generated by Django 4.0.3 on 2022-04-27 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc2022', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolhaprof',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 18, 43, 38, 581749), verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='escolhaprof',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='nota'),
        ),
    ]
