# Generated by Django 4.0.3 on 2022-06-14 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc2022', '0005_alter_escolhaprof_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolhaprof',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 1, 0, 631990), verbose_name='data'),
        ),
    ]
