# Generated by Django 4.0.3 on 2022-06-14 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc2022', '0006_alter_escolhaprof_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolhaprof',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 14, 28, 20, 361619), verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='escolhaprof',
            name='nota',
            field=models.IntegerField(blank=True, null=True, verbose_name='nota'),
        ),
    ]
