# Generated by Django 4.0.3 on 2022-06-28 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc2022', '0008_alter_escolhaprof_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolhaprof',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 2, 47, 21, 250703), verbose_name='data'),
        ),
    ]
