# Generated by Django 4.0.3 on 2022-06-28 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc2022', '0011_alter_escolhaprof_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolhaprof',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 0, 26, 27, 566850), verbose_name='data'),
        ),
    ]
