# Generated by Django 4.0.3 on 2022-06-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcc2022', '0013_alter_escolhaprof_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escolhaprof',
            name='data',
        ),
    ]
